name: iosApp
options:
  bundleIdPrefix: com.telegrammer
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

settings:
  base:
    DEVELOPMENT_TEAM: ""

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - iosApp
    settings:
      base:
        INFOPLIST_FILE: iosApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.telegrammer.ios
        PRODUCT_NAME: Telegrammer
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        FRAMEWORK_SEARCH_PATHS:
          - "$(SRCROOT)/../shared/build/bin/iosSimulatorArm64/debugFramework"
          - "$(SRCROOT)/../shared/build/bin/iosArm64/debugFramework"
        OTHER_LDFLAGS:
          - "-lsqlite3"
        SWIFT_VERSION: "5.9"
    preBuildScripts:
      - name: "Build KMP Shared Framework"
        script: |
          cd "$SRCROOT/.."
          export JAVA_HOME="/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home"
          export PATH="$JAVA_HOME/bin:$PATH"
          if [ "$PLATFORM_NAME" = "iphonesimulator" ]; then
            ./gradlew :shared:linkDebugFrameworkIosSimulatorArm64
          else
            ./gradlew :shared:linkDebugFrameworkIosArm64
          fi
        basedOnDependencyAnalysis: false
